guis:
  claim-java:
    name:
    lore:
      - "&7Owner: &e%owner%"
      - "&7World: &d%world%"
      - "&7Claim Size: &b%size%"
      - "&8%x%, %y%, %z%"
      - ""
      - "&7Click to teleport to claim!"
  claim-bedrock:
    name:
    lore:
      - "&7Owner: &e%owner%"
      - "&7World: &d%world%"
      - "&7Claim Size: &b%size%"
      - "&8%x%, %y%, %z%"
      - ""
      - "&7Click to teleport to claim!"
  background:
    material: GRAY_STAINED_GLASS_PANE
    data: 0
    display-name: ' '
    lore: []